In [1]:
name="1001=AFzal,1002=Prabodh,1003=nitesh,1004=sana,1005=pooja_maan"

In [2]:
name

'1001=AFzal,1002=Prabodh,1003=nitesh,1004=sana,1005=pooja_maan'

In [4]:
list_1=[var for var in range(10)]

In [5]:
list_2=[var for var in range(10)]

In [6]:
list_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list_2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
list_3=zip(list_1,list_2)#(0,0)..........

In [38]:
print(list_3)

In [39]:
dict(list_3)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}

In [25]:
x=iter("aFzal")

In [26]:
next(x)

'a'

In [27]:
next(x)

'F'

In [28]:
next(x)

'z'

In [30]:
next(x)

'a'

In [31]:
next(x)

'l'

In [32]:
next(x)

StopIteration: 

In [40]:
a=1,2,3

In [41]:
a

(1, 2, 3)

In [42]:
a,b=1,2

In [43]:
a

1

In [44]:
b

2

In [50]:
x=dict((a,b))

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [49]:
x

{1: 2}

In [51]:
y={"Name":"AFzal"}

In [52]:
len(y)

1

In [54]:
name="1001=AFzal,1002=Prabodh,1003=nitesh,1004=sana,1005=pooja_maan"#homework

In [56]:
x=[1,2]
y=(1,2)

In [57]:
2+2

4

In [58]:
"2"+"2"

'22'

In [59]:
2+2

4

In [60]:
"afzal"+"afzal"

'afzalafzal'

In [61]:
l=[1,2,3]
l2=[1,2,3]

In [62]:
l+l2

[1, 2, 3, 1, 2, 3]

In [63]:
l+1

TypeError: can only concatenate list (not "int") to list

In [64]:
import numpy as np

In [65]:
l

[1, 2, 3]

In [66]:
l=np.array(l)

In [67]:
l

array([1, 2, 3])

In [68]:
l+1

array([2, 3, 4])

In [69]:
l*23

array([23, 46, 69])

In [70]:
l=(1,2,3)

In [72]:
l2=(1,2,3)

In [73]:
l+l2

(1, 2, 3, 1, 2, 3)

In [74]:
s={1,2,3}
s2={3,4,5}

In [75]:
s+s2

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [76]:
5-7

-2

In [77]:
"afzal"-"nitesh"

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [79]:
"sana"-2

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [81]:
3/3

1.0

In [82]:
3534/32

110.4375

In [83]:
3*3

9

In [84]:
"Afzal"*"nitesh"

TypeError: can't multiply sequence by non-int of type 'str'

In [87]:
"AFzal"*3

'AFzalAFzalAFzal'

In [88]:
4//4

1

In [89]:
4/3

1.3333333333333333

In [90]:
4//3

1

In [91]:
3/2

1.5

In [94]:
number=int(input("Enter your number  :"))
if number%2==0 :
    print("Even")
else:
    print("Odd")

Enter your number  :0
Even


In [95]:
2**2

4

In [98]:
4**3

64

In [99]:
5+5-5

5

In [107]:
2**2%2

0

In [105]:
2%2**2

2

In [106]:
101%104

101

In [109]:
name

'1001=AFzal,1002=Prabodh,1003=nitesh,1004=sana,1005=pooja_maan'

In [119]:
name=input()

gjyfjhfjf677567567@@@@@


In [121]:
type(name)

str

In [122]:
name=int(input())

3443


In [123]:
type(name)

int

In [124]:
name=int(input())

,jgghcjhb


ValueError: invalid literal for int() with base 10: ',jgghcjhb'